services:
  - type: web
    name: oblivia-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
