workflows:
  android:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      flutter: stable
      java: openjdk11
      groups:
        - MY_SECRET_GROUP
      vars:
        API_KEY: 'your-api-key-here'
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install Dependencies
        script: |
          flutter pub get
          
      - name: Build APK
        script: |
          flutter build apk --release
          
      - name: Upload APK
        script: |
          cp build/app/outputs/flutter-apk/app-release.apk $CM_BUILD_DIR/app-release.apk
          curl -F "file=@$CM_BUILD_DIR/app-release.apk" https://your-upload-url.com
    cache:
      cache_paths:
        - ~/.pub-cache
        - build/
