workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        OPENAI_API_KEY: Encrypted_API_Key_Goes_Here
      android_signing:
        - my_keystore
    scripts:
      - name: Set up Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter --version
      - name: Install dependencies
        script: |
          cd android
          ./gradlew dependencies
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
