workflows:
  android:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      java: openjdk11
    # This is where we define the steps
    steps:
      - title: Install Dependencies
        script: |
          flutter pub get
          
      - title: Build APK
        script: |
          flutter build apk --release

      - title: Upload APK
        script: |
          cp build/app/outputs/flutter-apk/app-release.apk $CM_BUILD_DIR/app-release.apk
          curl -F "file=@$CM_BUILD_DIR/app-release.apk" https://your-upload-url.com

    # Define your environment variables for secure keys
    environment_variables:
      - name: API_KEY
        value: "your-api-key"
      - name: KEYSTORE_FILE
        value: "/path/to/your/keystore/file"
      - name: KEYSTORE_PASSWORD
        value: "your-keystore-password"
      - name: KEY_ALIAS
        value: "your-key-alias"
      - name: KEY_PASSWORD
        value: "your-key-password"
