workflows:
  android:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      java: openjdk11
      vars:
        # Define your environment variables for secure keys here
        API_KEY: "your-api-key"
        KEYSTORE_FILE: "/path/to/your/keystore/file"
        KEYSTORE_PASSWORD: "your-keystore-password"
        KEY_ALIAS: "your-key-alias"
        KEY_PASSWORD: "your-key-password"
    scripts:
      # This is where we define the steps
      - name: Install Dependencies
        script: |
          flutter pub get
          
      - name: Build APK
        script: |
          flutter build apk --release
          
      - name: Upload APK
        script: |
          cp build/app/outputs/flutter-apk/app-release.apk $CM_BUILD_DIR/app-release.apk
          curl -F "file=@$CM_BUILD_DIR/app-release.apk" https://your-upload-url.com
