workflows:
  flutter:
    name: Flutter Build
    max_build_duration: 60
    branches:
      only:
        - main
    environment:
      vars:
        - name: API_KEY
          value: ${{ secrets.API_KEY }} # API key as environment variable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    android:
      keystore:
        reference: my_keystore  # Name of your uploaded keystore
        password: ${{ secrets.KEYSTORE_PASSWORD }} # Keystore password (uploaded as secret in Codemagic)
        keyAlias: my_key_alias  # The alias you used when creating the keystore
        keyPassword: ${{ secrets.KEY_PASSWORD }} # The key password (uploaded as secret in Codemagic)
