workflows:
  flutter_build:
    name: Flutter Build
    max_build_duration: 60  # Optional: Limit the build duration (in minutes)
    environment:
      flutter: stable  # Use stable Flutter SDK
      vars:
        - name: API_KEY
          value: ${{ secrets.API_KEY }}  # Secret OpenAI API key
        - name: KEYSTORE_PASSWORD
          value: ${{ secrets.KEYSTORE_PASSWORD }}  # Keystore password (secret)
        - name: KEY_PASSWORD
          value: ${{ secrets.KEY_PASSWORD }}  # Key password inside the keystore (secret)
        - name: FLUTTER_BUILD_MODE
          value: release  # Build mode (release or debug)
    scripts:
      # Pre-build commands to prepare the app
      - flutter pub get  # Fetch dependencies
      - flutter clean  # Clean the project to avoid caching issues
      - flutter build apk --release  # Build APK in release mode

    android:
      keystore:
        file: ${{ secrets.KEYSTORE_FILE }}  # Keystore file uploaded in Codemagic secrets
        password: ${{ secrets.KEYSTORE_PASSWORD }}  # Keystore password
        keyAlias: ${{ secrets.KEY_ALIAS }}  # Alias for the key inside the keystore
        keyPassword: ${{ secrets.KEY_PASSWORD }}  # Key password for the alias inside the keystore

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Path to the output APK file

    # Optional: add any other necessary sections like testing, deployment, etc.
    # You can add testing sections here if needed.
