version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.09.1
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check Java version
          command: java -version
      - run:
          name: Grant Permission to gradlew
          command: chmod +x ./gradlew
      - run:
          name: List available tasks
          command: ./gradlew tasks || echo "Failed to list tasks"
      - run:
          name: Build APK
          command: ./gradlew assembleDebug || ./gradlew build
      - run:
          name: Find generated files
          command: find . -name "*.apk" || echo "No APK found"
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
workflows:
  build_apk:
    jobs:
      - build
