version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.09.1
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check Java version
          command: java -version
      - run:
          name: Grant Permission to gradlew and wrapper
          command: |
            chmod +x ./gradlew
            chmod 644 ./gradle/wrapper/gradle-wrapper.jar
      - run:
          name: Debug permissions
          command: |
            ls -la ./gradlew
            ls -la ./gradle/wrapper/
      - run:
          name: Build APK
          command: ./gradlew assembleDebug || ./gradlew build
      - run:
          name: Find generated files
          command: find . -name "*.apk" || echo "No APK found"
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
workflows:
  build_apk:
    jobs:
      - build
