name: Build APK for Kotlin Android App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@master
        
      # Step 2: Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@master
        with:
          java-version: '11'
          
      # Step 3: Make Gradle executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        
      # Step 4: Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          API_KEY: ${{ secrets.API_KEY }}
        
      # Step 5: List files (for debugging)
      - name: List output files
        run: find app/build/outputs -type f
      
      # Step 6: Create an artifact directory
      - name: Create artifact directory
        run: mkdir -p artifacts && cp app/build/outputs/apk/release/*.apk artifacts/
      
      # Step 7: Upload the APK using generic artifact upload
      - uses: actions/upload-artifact@master
        with:
          name: app-release
          path: artifacts
