name: Build APK for Kotlin Android App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v1
        
      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      # Step 3: Make Gradle executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        
      # Step 4: Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          API_KEY: ${{ secrets.API_KEY }}
        
      # Step 5: Find and upload the APK
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: app/build/outputs/apk/release/
