name: Build APK for Kotlin Android App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Basic checkout using git commands
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.ref_name }}
      
      # Debug - examine current files
      - name: Debug files
        run: |
          echo "=== Repository files ==="
          ls -la
          echo "=== Gradle wrapper directory ==="
          ls -la ./gradle/wrapper/ || echo "Wrapper directory not found"
          echo "=== Examine gradlew script ==="
          cat ./gradlew || echo "No gradlew file found"
      
      # Setup Java manually
      - name: Set up JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version
      
      # Create a new gradlew script that bypasses the jar issue
      - name: Create new gradlew script
        run: |
          # Install Gradle
          sudo apt-get install -y gradle
          
          # Create and use a new script that uses the system Gradle
          echo '#!/bin/bash' > ./build-with-gradle.sh
          echo 'gradle "$@"' >> ./build-with-gradle.sh
          chmod +x ./build-with-gradle.sh
          
          # Display the script
          echo "=== New build script ==="
          cat ./build-with-gradle.sh
      
      # Build the APK with the new script
      - name: Build APK
        run: |
          ./build-with-gradle.sh assembleRelease --info
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      # Debug - list all APK files
      - name: Find APK files
        if: success() || failure()
        run: |
          echo "=== APK files ==="
          find . -name "*.apk" || echo "No APK files found"
          
      # Create a release tag (if on main branch)
      - name: Create Release Tag
        if: github.ref == 'refs/heads/main' && success()
        run: |
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "release-$BUILD_NUMBER" -m "Release build $BUILD_NUMBER"
          git push origin "release-$BUILD_NUMBER"
