name: Build APK for Kotlin Android App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # Step 2: Set up JDK 11 (required for Android builds)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      # Step 3: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
          
      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # Step 5: Make Gradle executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        
      # Step 6: Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease
        
      # Step 7: Upload APK as Artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk
