name: Build APK

on:
  push:
    branches:
      - main  # Trigger the build when code is pushed to the 'main' branch.
  pull_request:
    branches:
      - main  # Trigger the build on pull requests to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu as the runner environment.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository.

      - name: Set up JDK
        uses: actions/setup-java@v2  # Setting up the Java Development Kit.
        with:
          java-version: '11'  # Use the version of Java you want, 11 is a good default for Android.

      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-manager-action@v2
        with:
          sdk-tools: "cmdline-tools;latest"  # Set up the latest command-line tools.

      - name: Cache Android dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: ./gradlew assembleRelease  # This builds the release APK. Use assembleDebug for debug APK.

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk  # Name of the APK artifact to upload.
          path: app/build/outputs/apk/release/app-release.apk  # Path to the APK generated after the build.
