name: Build APK for Kotlin Android App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2
        
      # Step 2: Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      # Step 3: Make Gradle executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        
      # Step 4: Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          API_KEY: ${{ secrets.API_KEY }}
        
      # Step 5: List files (for debugging)
      - name: List output files
        run: find app/build/outputs -type f || echo "No output files found"
      
      # Step 6: Upload using basic command line
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
