name: Build APK for Kotlin Android App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Basic checkout using git commands
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.ref_name }}
          
      # Setup Java manually
      - name: Set up JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version
          
      # Build the APK
      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --info
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      # Debug - list all APK files
      - name: Find APK files
        run: |
          echo "=== APK files ==="
          find . -name "*.apk"
          
      # Create a release tag (if on main branch)
      - name: Create Release Tag
        if: github.ref == 'refs/heads/main'
        run: |
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "release-$BUILD_NUMBER" -m "Release build $BUILD_NUMBER"
          git push origin "release-$BUILD_NUMBER"
