name: Kotlin Android Build

on:
  push:
    branches:
      - main  # Trigger build on push to main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use macOS if required for your app, e.g., macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Set up Android SDK (install necessary components)
      - name: Set up Android SDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android
          echo "y" | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android --install "build-tools;30.0.3" "platforms;android-30"

      # Step 4: Configure your API Key in the environment (from GitHub Secrets)
      - name: Set environment variable for API key
        run: echo "MY_API_KEY=${{ secrets.MY_API_KEY }}" >> $GITHUB_ENV

      # Step 5: Build the APK
      - name: Build the APK
        run: |
          ./gradlew assembleRelease

      # Step 6: Upload APK as build artifact (so you can download it after)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
